name: ragbot
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.11.9
  - pip=24.2
  - pip:
      - python-dotenv==1.0.1
      - weave==0.51.29
      - fastapi[standard]==0.115.4
      - uvicorn[standard]==0.32.0
      - python-multipart==0.0.18
      - pydantic==2.9.2
      - pydantic-settings==2.6.1
      - aiofiles==24.1.0
      - langchain==0.3.7
      - langchain-community==0.3.5
      - langchain-text-splitters==0.3.2
      - langchain-unstructured==0.1.6
      - unstructured==0.16.23
      - PyMuPDF==1.24.13
      - motor==3.6.0
      - openai==1.55.3
      - qdrant-client==1.12.1
      - beautifulsoup4==4.12.3
      - Wikipedia-API==0.7.1
